# global.R - V2 Data Preprocessing and Shared Functions

library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(ggplot2)
library(dplyr)
library(tidyr)
library(plotly)
library(DT)
library(scales)
library(xgboost)
library(caret)
library(knitr)
library(kableExtra)
if (requireNamespace("pagedown", quietly = TRUE)) library(pagedown)

# ============================================================
# V2 COLOR PALETTE — Modern, accessible
# ============================================================
v2_colors <- list(
  cu        = "#2563EB",   # Blue 600
  noncu     = "#DC2626",   # Red 600
  cu_light  = "#BFDBFE",   # Blue 100
  noncu_light = "#FECACA", # Red 100
  positive  = "#16A34A",   # Green 600
  negative  = "#DC2626",
  neutral   = "#64748B",   # Slate 500
  bg        = "#F8FAFC",
  card      = "#FFFFFF",
  border    = "#E2E8F0",
  text_primary   = "#0F172A",
  text_secondary = "#475569",
  accent    = "#7C3AED"    # Violet 600 (accent)
)

# ============================================================
# VARIABLE LABELS — sourced directly from nsmo_v60_labels.sas
# 572 variables total (survey + supplementary)
# ============================================================
variable_labels <- list(
  "age_o1" = "Age: Other Borrower 1",
  "age_o2" = "Age: Other Borrower 2",
  "age_o3" = "Age: Other Borrower 3",
  "analysis_weight" = "NSMO Analysis Weight (Sampling Weight x Non-response Adjustment)",
  "borrower_num" = "Number of Borrowers at Origination",
  "borrower_r" = "Flag Indicating Respondent is a Borrower",
  "borrower_s" = "Flag Indicating Spouse/Partner is a Borrower",
  "cashout" = "Flag Indicating Cashout Refinance",
  "close_month" = "Mortgage Termination Month",
  "close_status_1224" = "Mortgage Termination Status in December 2024",
  "close_year" = "Mortgage Termination Year",
  "cltv" = "Mortgage Combined Loan-to-Value Ratio at Origination (Percent)",
  "cu" = "Credit Union",
  "dti" = "Mortgage Debt-to-Income (Back End) Ratio at Origination (Percent)",
  "first_mort_o1" = "Flag Indicating First Mortgage in Credit File: Other Borrower 1",
  "first_mort_o2" = "Flag Indicating First Mortgage in Credit File: Other Borrower 2",
  "first_mort_o3" = "Flag Indicating First Mortgage in Credit File: Other Borrower 3",
  "first_mort_r" = "Flag Indicating First Mortgage in Credit File: Respondent",
  "first_mort_s" = "Flag Indicating First Mortgage in Credit File: Spouse/Partner",
  "forb0320" = "Flag Indicating Forbearance Status, March 2020",
  "forb0321" = "Flag Indicating Forbearance Status, March 2021",
  "forb0322" = "Flag Indicating Forbearance Status, March 2022",
  "forb0323" = "Flag Indicating Forbearance Status, March 2023",
  "forb0324" = "Flag Indicating Forbearance Status, March 2024",
  "forb0620" = "Flag Indicating Forbearance Status, June 2020",
  "forb0621" = "Flag Indicating Forbearance Status, June 2021",
  "forb0622" = "Flag Indicating Forbearance Status, June 2022",
  "forb0623" = "Flag Indicating Forbearance Status, June 2023",
  "forb0624" = "Flag Indicating Forbearance Status, June 2024",
  "forb0920" = "Flag Indicating Forbearance Status, September 2020",
  "forb0921" = "Flag Indicating Forbearance Status, September 2021",
  "forb0922" = "Flag Indicating Forbearance Status, September 2022",
  "forb0923" = "Flag Indicating Forbearance Status, September 2023",
  "forb0924" = "Flag Indicating Forbearance Status, September 2024",
  "forb1220" = "Flag Indicating Forbearance Status, December 2020",
  "forb1221" = "Flag Indicating Forbearance Status, December 2021",
  "forb1222" = "Flag Indicating Forbearance Status, December 2022",
  "forb1223" = "Flag Indicating Forbearance Status, December 2023",
  "forb1224" = "Flag Indicating Forbearance Status, December 2024",
  "gse" = "Government Sponsored Enterprise",
  "jumbo" = "Flag Indicating Jumbo Mortgage Loan at Origination",
  "loan_amount_cat" = "Mortgage Loan Amount at Origination (Categorical)",
  "loan_type" = "Mortgage Type",
  "ltv" = "Mortgage Loan-to-Value Ratio at Origination (Percent)",
  "metro_lmi" = "Flag Indicating Metropolitan CRA Low to Moderate Income Tract",
  "mtmltv0313" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2013",
  "mtmltv0314" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2014",
  "mtmltv0315" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2015",
  "mtmltv0316" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2016",
  "mtmltv0317" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2017",
  "mtmltv0318" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2018",
  "mtmltv0319" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2019",
  "mtmltv0320" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2020",
  "mtmltv0321" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2021",
  "mtmltv0322" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2022",
  "mtmltv0323" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2023",
  "mtmltv0324" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, March 2024",
  "mtmltv0613" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2013",
  "mtmltv0614" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2014",
  "mtmltv0615" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2015",
  "mtmltv0616" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2016",
  "mtmltv0617" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2017",
  "mtmltv0618" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2018",
  "mtmltv0619" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2019",
  "mtmltv0620" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2020",
  "mtmltv0621" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2021",
  "mtmltv0622" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2022",
  "mtmltv0623" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2023",
  "mtmltv0624" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, June 2024",
  "mtmltv0913" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2013",
  "mtmltv0914" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2014",
  "mtmltv0915" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2015",
  "mtmltv0916" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2016",
  "mtmltv0917" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2017",
  "mtmltv0918" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2018",
  "mtmltv0919" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2019",
  "mtmltv0920" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2020",
  "mtmltv0921" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2021",
  "mtmltv0922" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2022",
  "mtmltv0923" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2023",
  "mtmltv0924" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, September 2024",
  "mtmltv1213" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2013",
  "mtmltv1214" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2014",
  "mtmltv1215" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2015",
  "mtmltv1216" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2016",
  "mtmltv1217" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2017",
  "mtmltv1218" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2018",
  "mtmltv1219" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2019",
  "mtmltv1220" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2020",
  "mtmltv1221" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2021",
  "mtmltv1222" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2022",
  "mtmltv1223" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2023",
  "mtmltv1224" = "Mark-to-Market Loan-to-Value Ratio of the Mortgage, December 2024",
  "nsmoid" = "NSMO Identification Number",
  "open_month" = "Mortgage Origination Month",
  "open_year" = "Mortgage Origination Year",
  "perf_status_0313" = "Mortgage Performance Status in March 2013",
  "perf_status_0314" = "Mortgage Performance Status in March 2014",
  "perf_status_0315" = "Mortgage Performance Status in March 2015",
  "perf_status_0316" = "Mortgage Performance Status in March 2016",
  "perf_status_0317" = "Mortgage Performance Status in March 2017",
  "perf_status_0318" = "Mortgage Performance Status in March 2018",
  "perf_status_0319" = "Mortgage Performance Status in March 2019",
  "perf_status_0320" = "Mortgage Performance Status in March 2020",
  "perf_status_0321" = "Mortgage Performance Status in March 2021",
  "perf_status_0322" = "Mortgage Performance Status in March 2022",
  "perf_status_0323" = "Mortgage Performance Status in March 2023",
  "perf_status_0324" = "Mortgage Performance Status in March 2024",
  "perf_status_0613" = "Mortgage Performance Status in June 2013",
  "perf_status_0614" = "Mortgage Performance Status in June 2014",
  "perf_status_0615" = "Mortgage Performance Status in June 2015",
  "perf_status_0616" = "Mortgage Performance Status in June 2016",
  "perf_status_0617" = "Mortgage Performance Status in June 2017",
  "perf_status_0618" = "Mortgage Performance Status in June 2018",
  "perf_status_0619" = "Mortgage Performance Status in June 2019",
  "perf_status_0620" = "Mortgage Performance Status in June 2020",
  "perf_status_0621" = "Mortgage Performance Status in June 2021",
  "perf_status_0622" = "Mortgage Performance Status in June 2022",
  "perf_status_0623" = "Mortgage Performance Status in June 2023",
  "perf_status_0624" = "Mortgage Performance Status in June 2024",
  "perf_status_0913" = "Mortgage Performance Status in September 2013",
  "perf_status_0914" = "Mortgage Performance Status in September 2014",
  "perf_status_0915" = "Mortgage Performance Status in September 2015",
  "perf_status_0916" = "Mortgage Performance Status in September 2016",
  "perf_status_0917" = "Mortgage Performance Status in September 2017",
  "perf_status_0918" = "Mortgage Performance Status in September 2018",
  "perf_status_0919" = "Mortgage Performance Status in September 2019",
  "perf_status_0920" = "Mortgage Performance Status in September 2020",
  "perf_status_0921" = "Mortgage Performance Status in September 2021",
  "perf_status_0922" = "Mortgage Performance Status in September 2022",
  "perf_status_0923" = "Mortgage Performance Status in September 2023",
  "perf_status_0924" = "Mortgage Performance Status in September 2024",
  "perf_status_1213" = "Mortgage Performance Status in December 2013",
  "perf_status_1214" = "Mortgage Performance Status in December 2014",
  "perf_status_1215" = "Mortgage Performance Status in December 2015",
  "perf_status_1216" = "Mortgage Performance Status in December 2016",
  "perf_status_1217" = "Mortgage Performance Status in December 2017",
  "perf_status_1218" = "Mortgage Performance Status in December 2018",
  "perf_status_1219" = "Mortgage Performance Status in December 2019",
  "perf_status_1220" = "Mortgage Performance Status in December 2020",
  "perf_status_1221" = "Mortgage Performance Status in December 2021",
  "perf_status_1222" = "Mortgage Performance Status in December 2022",
  "perf_status_1223" = "Mortgage Performance Status in December 2023",
  "perf_status_1224" = "Mortgage Performance Status in December 2024",
  "pmms" = "Freddie Mac\'s Primary Mortgage Market Survey (PMMS) Rate at Origination (Percent)",
  "pti" = "Mortgage Payment-to-Income (Front End) Ratio at Origination (Percent)",
  "rate_spread" = "Mortgage Interest Rate Spread at Origination (Percent)",
  "score_0313_r" = "VantageScore 3.0 in March 2013: Respondent",
  "score_0313_s" = "VantageScore 3.0 in March 2013: Spouse/Partner",
  "score_0314_r" = "VantageScore 3.0 in March 2014: Respondent",
  "score_0314_s" = "VantageScore 3.0 in March 2014: Spouse/Partner",
  "score_0315_r" = "VantageScore 3.0 in March 2015: Respondent",
  "score_0315_s" = "VantageScore 3.0 in March 2015: Spouse/Partner",
  "score_0316_r" = "VantageScore 3.0 in March 2016: Respondent",
  "score_0316_s" = "VantageScore 3.0 in March 2016: Spouse/Partner",
  "score_0317_r" = "VantageScore 3.0 in March 2017: Respondent",
  "score_0317_s" = "VantageScore 3.0 in March 2017: Spouse/Partner",
  "score_0318_r" = "VantageScore 3.0 in March 2018: Respondent",
  "score_0318_s" = "VantageScore 3.0 in March 2018: Spouse/Partner",
  "score_0319_r" = "VantageScore 3.0 in March 2019: Respondent",
  "score_0319_s" = "VantageScore 3.0 in March 2019: Spouse/Partner",
  "score_0320_r" = "VantageScore 3.0 in March 2020: Respondent",
  "score_0320_s" = "VantageScore 3.0 in March 2020: Spouse/Partner",
  "score_0321_r" = "VantageScore 3.0 in March 2021: Respondent",
  "score_0321_s" = "VantageScore 3.0 in March 2021: Spouse/Partner",
  "score_0322_r" = "VantageScore 3.0 in March 2022: Respondent",
  "score_0322_s" = "VantageScore 3.0 in March 2022: Spouse/Partner",
  "score_0323_r" = "VantageScore 3.0 in March 2023: Respondent",
  "score_0323_s" = "VantageScore 3.0 in March 2023: Spouse/Partner",
  "score_0324_r" = "VantageScore 3.0 in March 2024: Respondent",
  "score_0324_s" = "VantageScore 3.0 in March 2024: Spouse/Partner",
  "score_0613_r" = "VantageScore 3.0 in June 2013: Respondent",
  "score_0613_s" = "VantageScore 3.0 in June 2013: Spouse/Partner",
  "score_0614_r" = "VantageScore 3.0 in June 2014: Respondent",
  "score_0614_s" = "VantageScore 3.0 in June 2014: Spouse/Partner",
  "score_0615_r" = "VantageScore 3.0 in June 2015: Respondent",
  "score_0615_s" = "VantageScore 3.0 in June 2015: Spouse/Partner",
  "score_0616_r" = "VantageScore 3.0 in June 2016: Respondent",
  "score_0616_s" = "VantageScore 3.0 in June 2016: Spouse/Partner",
  "score_0617_r" = "VantageScore 3.0 in June 2017: Respondent",
  "score_0617_s" = "VantageScore 3.0 in June 2017: Spouse/Partner",
  "score_0618_r" = "VantageScore 3.0 in June 2018: Respondent",
  "score_0618_s" = "VantageScore 3.0 in June 2018: Spouse/Partner",
  "score_0619_r" = "VantageScore 3.0 in June 2019: Respondent",
  "score_0619_s" = "VantageScore 3.0 in June 2019: Spouse/Partner",
  "score_0620_r" = "VantageScore 3.0 in June 2020: Respondent",
  "score_0620_s" = "VantageScore 3.0 in June 2020: Spouse/Partner",
  "score_0621_r" = "VantageScore 3.0 in June 2021: Respondent",
  "score_0621_s" = "VantageScore 3.0 in June 2021: Spouse/Partner",
  "score_0622_r" = "VantageScore 3.0 in June 2022: Respondent",
  "score_0622_s" = "VantageScore 3.0 in June 2022: Spouse/Partner",
  "score_0623_r" = "VantageScore 3.0 in June 2023: Respondent",
  "score_0623_s" = "VantageScore 3.0 in June 2023: Spouse/Partner",
  "score_0624_r" = "VantageScore 3.0 in June 2024: Respondent",
  "score_0624_s" = "VantageScore 3.0 in June 2024: Spouse/Partner",
  "score_0913_r" = "VantageScore 3.0 in September 2013: Respondent",
  "score_0913_s" = "VantageScore 3.0 in September 2013: Spouse/Partner",
  "score_0914_r" = "VantageScore 3.0 in September 2014: Respondent",
  "score_0914_s" = "VantageScore 3.0 in September 2014: Spouse/Partner",
  "score_0915_r" = "VantageScore 3.0 in September 2015: Respondent",
  "score_0915_s" = "VantageScore 3.0 in September 2015: Spouse/Partner",
  "score_0916_r" = "VantageScore 3.0 in September 2016: Respondent",
  "score_0916_s" = "VantageScore 3.0 in September 2016: Spouse/Partner",
  "score_0917_r" = "VantageScore 3.0 in September 2017: Respondent",
  "score_0917_s" = "VantageScore 3.0 in September 2017: Spouse/Partner",
  "score_0918_r" = "VantageScore 3.0 in September 2018: Respondent",
  "score_0918_s" = "VantageScore 3.0 in September 2018: Spouse/Partner",
  "score_0919_r" = "VantageScore 3.0 in September 2019: Respondent",
  "score_0919_s" = "VantageScore 3.0 in September 2019: Spouse/Partner",
  "score_0920_r" = "VantageScore 3.0 in September 2020: Respondent",
  "score_0920_s" = "VantageScore 3.0 in September 2020: Spouse/Partner",
  "score_0921_r" = "VantageScore 3.0 in September 2021: Respondent",
  "score_0921_s" = "VantageScore 3.0 in September 2021: Spouse/Partner",
  "score_0922_r" = "VantageScore 3.0 in September 2022: Respondent",
  "score_0922_s" = "VantageScore 3.0 in September 2022: Spouse/Partner",
  "score_0923_r" = "VantageScore 3.0 in September 2023: Respondent",
  "score_0923_s" = "VantageScore 3.0 in September 2023: Spouse/Partner",
  "score_0924_r" = "VantageScore 3.0 in September 2024: Respondent",
  "score_0924_s" = "VantageScore 3.0 in September 2024: Spouse/Partner",
  "score_1213_r" = "VantageScore 3.0 in December 2013: Respondent",
  "score_1213_s" = "VantageScore 3.0 in December 2013: Spouse/Partner",
  "score_1214_r" = "VantageScore 3.0 in December 2014: Respondent",
  "score_1214_s" = "VantageScore 3.0 in December 2014: Spouse/Partner",
  "score_1215_r" = "VantageScore 3.0 in December 2015: Respondent",
  "score_1215_s" = "VantageScore 3.0 in December 2015: Spouse/Partner",
  "score_1216_r" = "VantageScore 3.0 in December 2016: Respondent",
  "score_1216_s" = "VantageScore 3.0 in December 2016: Spouse/Partner",
  "score_1217_r" = "VantageScore 3.0 in December 2017: Respondent",
  "score_1217_s" = "VantageScore 3.0 in December 2017: Spouse/Partner",
  "score_1218_r" = "VantageScore 3.0 in December 2018: Respondent",
  "score_1218_s" = "VantageScore 3.0 in December 2018: Spouse/Partner",
  "score_1219_r" = "VantageScore 3.0 in December 2019: Respondent",
  "score_1219_s" = "VantageScore 3.0 in December 2019: Spouse/Partner",
  "score_1220_r" = "VantageScore 3.0 in December 2020: Respondent",
  "score_1220_s" = "VantageScore 3.0 in December 2020: Spouse/Partner",
  "score_1221_r" = "VantageScore 3.0 in December 2021: Respondent",
  "score_1221_s" = "VantageScore 3.0 in December 2021: Spouse/Partner",
  "score_1222_r" = "VantageScore 3.0 in December 2022: Respondent",
  "score_1222_s" = "VantageScore 3.0 in December 2022: Spouse/Partner",
  "score_1223_r" = "VantageScore 3.0 in December 2023: Respondent",
  "score_1223_s" = "VantageScore 3.0 in December 2023: Spouse/Partner",
  "score_1224_r" = "VantageScore 3.0 in December 2024: Respondent",
  "score_1224_s" = "VantageScore 3.0 in December 2024: Spouse/Partner",
  "score_orig_o1" = "VantageScore 3.0 at Origination: Other Borrower 1",
  "score_orig_o2" = "VantageScore 3.0 at Origination: Other Borrower 2",
  "score_orig_o3" = "VantageScore 3.0 at Origination: Other Borrower 3",
  "score_orig_r" = "VantageScore 3.0 at Origination: Respondent",
  "score_orig_s" = "VantageScore 3.0 at Origination: Spouse/Partner",
  "sex_o1" = "Sex: Other Borrower 1",
  "sex_o2" = "Sex: Other Borrower 2",
  "sex_o3" = "Sex: Other Borrower 3",
  "survey_wave" = "NSMO Survey Wave (Quarterly)",
  "term" = "Mortgage Term (in Years) at Origination",
  "x05a" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05b" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05c" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05d" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05e" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05f" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x05g" = "When you began the process of getting this mortgage, how familiar were you (and any co-signers) with each of the foll...",
  "x06" = "When you began the process of getting this mortgage, how concerned were you about qualifying for a mortgage?",
  "x07" = "How firm an idea did you have about the mortgage you wanted?",
  "x08a" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Your mort...",
  "x08b" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Other mor...",
  "x08c" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Real esta...",
  "x08d" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Material ...",
  "x08e" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Websites ...",
  "x08f" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Newspaper...",
  "x08g" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Friends/r...",
  "x08h" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Bankers, ...",
  "x08i" = "How much did you use each of the following sources to get information about mortgages or mortgage lenders?: Housing c...",
  "x09" = "Which one of the following best describes your shopping process?",
  "x10" = "Which one of the following best describes how you applied for this mortgage?",
  "x11" = "How many different mortgage lenders/brokers did you seriously consider before choosing where to apply for this mortgage?",
  "x12" = "How many different mortgage lenders/brokers did you end up applying to?",
  "x13a" = "Did you apply to more than one mortgage lender/broker for any of the following reasons?: Searching for better loan terms",
  "x13b" = "Did you apply to more than one mortgage lender/broker for any of the following reasons?: Concern over qualifying for ...",
  "x13c" = "Did you apply to more than one mortgage lender/broker for any of the following reasons?: Information learned from the...",
  "x13d" = "Did you apply to more than one mortgage lender/broker for any of the following reasons?: Turned down on earlier appli...",
  "x14a" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14a_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Havin...",
  "x14b" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14b_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Havin...",
  "x14c" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14c_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Used ...",
  "x14d" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14d_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Lende...",
  "x14e" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14f" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14f_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Recom...",
  "x14g" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14g_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Recom...",
  "x14h" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14h_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Reput...",
  "x14i" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14i_1" = "How important were each of the following in choosing the lender/broker you used for the mortgage you took out?: Spoke...",
  "x14j" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x14k" = "How important were each of the following in choosing the mortgage lender/broker you used for the mortgage you took ou...",
  "x15" = "Who initiated the first contact between you and the mortgage lender/broker you used for the mortgage you took out?",
  "x16" = "How open were you to suggestions from your mortgage lender/broker about mortgages with different features or terms?",
  "x1601" = "While you were getting your mortgage, how did you primarily interact with your mortgage lender/broker? (Waves 35-42)",
  "x17a" = "How important were each of the following in determining the mortgage you took out?: Lower interest rate (Waves 7-42)",
  "x17a_1" = "How important were each of the following in determining the mortgage you took out?: Low interest rate (Waves 1-6)",
  "x17b" = "How important were each of the following in determining the mortgage you took out?: Lower APR (Annual Percentage Rate...",
  "x17b_1" = "How important were each of the following in determining the mortgage you took out?: Low APR (Annual Percentage Rate) ...",
  "x17c" = "How important were each of the following in determining the mortgage you took out?: Lower closing fees (Waves 7-42)",
  "x17c_1" = "How important were each of the following in determining the mortgage you took out?: Low closing fees (Waves 1-6)",
  "x17d" = "How important were each of the following in determining the mortgage you took out?: Lower down payment (Waves 7-42)",
  "x17d_1" = "How important were each of the following in determining the mortgage you took out?: Low down payment(Waves 1-6)",
  "x17e" = "How important were each of the following in determining the mortgage you took out?: Lower monthly payment (Waves 7-42)",
  "x17e_1" = "How important were each of the following in determining the mortgage you took out?: Low monthly payment (Waves 1-6)",
  "x17f" = "How important were each of the following in determining the mortgage you took out?: An interest rate fixed for the li...",
  "x17f_1" = "How important were each of the following in determining the mortgage you took out?: An interest rate fixed for the li...",
  "x17g" = "How important were each of the following in determining the mortgage you took out?: A term of 30 years (Waves 7-42)",
  "x17g_1" = "How important were each of the following in determining the mortgage you took out?: A term of less than 30 years (Wav...",
  "x17h" = "How important were each of the following in determining the mortgage you took out?: No mortgage insurance (Waves 7-42)",
  "x17h_1" = "How important were each of the following in determining the mortgage you took out?: No mortgage insurance (Waves 1-6)",
  "x18" = "Your lender may have given you a booklet \'Your home loan toolkit: A step-by-step guide,\' do you remember receiving ...",
  "x19" = "Did the \'Your home loan toolkit\' booklet lead you to ask additional questions about your mortgage terms? (Waves 7-34)",
  "x20a" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Have to add another co-signer t...",
  "x20b" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Resolve credit report errors or...",
  "x20c" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Answer follow-up requests for m...",
  "x20d" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Have more than one appraisal",
  "x20e" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Redo/refile paperwork due to pr...",
  "x20f" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Delay or postpone closing date",
  "x20g" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Have your \'Loan Estimate\' rev...",
  "x20h" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Check other sources to confirm ...",
  "x20i" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Get documents in your primary l...",
  "x20j" = "In the process of getting this mortgage from your mortgage lender/broker, did you...: Have the lender/broker translat...",
  "x21a" = "Did the \'Loan Estimate\' you received from your mortgage lender/broker...: Have easy to understand information",
  "x21b" = "Did the \'Loan Estimate\' you received from your mortgage lender/broker...: Contain valuable information",
  "x21c" = "Did the \'Loan Estimate\' you received from your mortgage lender/broker...: Cause you to take an action, such as seek...",
  "x22a" = "Did the \'Loan Estimate\' lead you to...: Ask questions of your mortgage lender/broker (Waves 1-34)",
  "x22b" = "Did the \'Loan Estimate\' lead you to...: Seek a change in your loan or closing (Waves 1-34)",
  "x22c" = "Did the \'Loan Estimate\' lead you to...: Apply to a different mortgage lender/broker (Waves 11-34)",
  "x23a" = "During the application process were you told about mortgages with any of the following?: An interest rate that is fix...",
  "x23b" = "During the application process were you told about mortgages with any of the following?: An interest rate that could ...",
  "x23c" = "During the application process were you told about mortgages with any of the following?: A term of less than 30 years",
  "x23d" = "During the application process were you told about mortgages with any of the following?: A higher interest rate in re...",
  "x23e" = "During the application process were you told about mortgages with any of the following?: A lower interest rate in ret...",
  "x23f" = "During the application process were you told about mortgages with any of the following?: Interest-only monthly payments",
  "x23g" = "During the application process were you told about mortgages with any of the following?: An escrow account for taxes ...",
  "x23h" = "During the application process were you told about mortgages with any of the following?: A prepayment penalty (fee if...",
  "x23i" = "During the application process were you told about mortgages with any of the following?: Reduced documentation or \'e...",
  "x23j" = "During the application process were you told about mortgages with any of the following?: An FHA, VA, USDA or Rural Ho...",
  "x24a" = "In selecting your settlement/closing agent did you use someone...: Selected/recommended by the mortgage lender/broker...",
  "x24b" = "In selecting your settlement/closing agent did you use someone...: You used previously",
  "x24c" = "In selecting your settlement/closing agent did you use someone...: Found shopping around",
  "x24z" = "In selecting your settlement/closing agent did you use someone...: Did not have a settlement/closing agent (Waves 11-42)",
  "x25" = "Do you have title insurance on this mortgage? (Waves 11-42)",
  "x25_1" = "Did your lender require you to get title insurance on this mortgage? (Waves 1-10)",
  "x26" = "Which one best describes how you picked the title insurance?",
  "x27a" = "Overall, how satisfied are you that the mortgage you got was the one with the...: Best terms to fit your needs",
  "x27b" = "Overall, how satisfied are you that the mortgage you got was the one with the...: Lowest interest rate for which you ...",
  "x27c" = "Overall, how satisfied are you that the mortgage you got was the one with the...: Lowest closing costs",
  "x28a" = "Overall, how satisfied are you with the...: Mortgage lender/broker you used",
  "x28b" = "Overall, how satisfied are you with the...: Application process",
  "x28c" = "Overall, how satisfied are you with the...: Documentation process required for the loan (Waves 7-42)",
  "x28d" = "Overall, how satisfied are you with the...: Loan closing process",
  "x28e" = "Overall, how satisfied are you with the...: Information in mortgage disclosure documents",
  "x28f" = "Overall, how satisfied are you with the...: Timeliness of mortgage disclosure documents",
  "x28g" = "Overall, how satisfied are you with the...: Settlement agent",
  "x28h" = "Overall, how satisfied are you with the...: Property appraisal (Waves 31-42)",
  "x29" = "Did you take a course about home-buying or talk to a professional housing counselor?",
  "x30a" = "Was your home-buying course or counseling...: In person, one-on-one",
  "x30b" = "Was your home-buying course or counseling...: In person, in a group",
  "x30c" = "Was your home-buying course or counseling...: Over the phone",
  "x30d" = "Was your home-buying course or counseling...: Online",
  "x30e" = "Was your home-buying course or counseling...: Required (Waves 19-42)",
  "x31" = "How many hours was your home-buying course or counseling?",
  "x32" = "Overall, how helpful was your home-buying course or counseling?",
  "x33" = "Which one of these reasons best describes this most recent mortgage?",
  "x34a" = "Did you do the following before or after you made an offer on this house or property?: Contacted a lender to explore ...",
  "x34b" = "Did you do the following before or after you made an offer on this house or property?: Got a pre-approval or pre-qual...",
  "x34c" = "Did you do the following before or after you made an offer on this house or property?: Decided on the type of loan (W...",
  "x34d" = "Did you do the following before or after you made an offer on this house or property?: Made a decision on which lende...",
  "x34e" = "Did you do the following before or after you made an offer on this house or property?: Submitted an official loan app...",
  "x36a" = "Did you use any of the following sources of funds to buy this property?: Proceeds from the sale of another property",
  "x36b" = "Did you use any of the following sources of funds to buy this property?: Savings, retirement account, inheritance, or...",
  "x36c" = "Did you use any of the following sources of funds to buy this property?: Assistance or loan from a nonprofit or gover...",
  "x36d" = "Did you use any of the following sources of funds to buy this property?: A second lien, home equity loan, or home equ...",
  "x36e" = "Did you use any of the following sources of funds to buy this property?: Gift or loan from family or friend",
  "x36f" = "Did you use any of the following sources of funds to buy this property?: Seller contribution",
  "x37a" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Change to a fixed-...",
  "x37a_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37b" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Get a lower intere...",
  "x37b_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37c" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Get a lower monthl...",
  "x37c_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37d" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Consolidate or pay...",
  "x37d_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37e" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Repay the loan mor...",
  "x37e_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37f" = "How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Take out cash (Wav...",
  "x37f_1" = "How important, if at all, were the following reasons in your decision to refinance, modify, or obtain a new mortgage?...",
  "x37g" = ": How important were the following in your decision to refinance, modify, or obtain a new mortgage?: Remove private m...",
  "x40a" = "Did you use the money you got from this new mortgage for any of the following?: College expenses",
  "x40b" = "Did you use the money you got from this new mortgage for any of the following?: Auto or other major purchase",
  "x40c" = "Did you use the money you got from this new mortgage for any of the following?: Buy out co-signer(s)/co-owner(s) (Wav...",
  "x40d" = "Did you use the money you got from this new mortgage for any of the following?: Pay off other bills or debts",
  "x40e" = "Did you use the money you got from this new mortgage for any of the following?: Home repairs or new construction",
  "x40f" = "Did you use the money you got from this new mortgage for any of the following?: Savings",
  "x40g" = "Did you use the money you got from this new mortgage for any of the following?: Closing costs of new mortgage",
  "x40h" = "Did you use the money you got from this new mortgage for any of the following?: Business or investment",
  "x40x" = "Did you use the money you got from this new mortgage for any of the following?: Other (specify)",
  "x40z" = "Did you use the money you got from this new mortgage for any of the following?: Did not get money from refinancing (W...",
  "x44" = "Does this mortgage have...: An adjustable rate (one that can change over the life of the loan)?",
  "x45" = "Which one of the following best describes how you decided on the interest rate of your mortgage? (Waves 19-42)",
  "x46a" = "Does this mortgage have...: A prepayment penalty (fee if the mortgage is paid off early)",
  "x46b" = "Does this mortgage have...: An escrow account for taxes and/or homeowner insurance",
  "x46c" = "Does this mortgage have...: A balloon payment",
  "x46d" = "Does this mortgage have...: Interest-only payments",
  "x46e" = "Does this mortgage have...: Private mortgage insurance (Waves 11-42)",
  "x46f" = "Does this mortgage have...: Lender-required flood insurance (Waves 35-42)",
  "x48a" = "How were the total closing costs (loan costs and other costs) for this loan paid?: By me or a co-signer with a check ...",
  "x48b" = "How were the total closing costs (loan costs and other costs) for this loan paid?: Added to the mortgage amount",
  "x48c" = "How were the total closing costs (loan costs and other costs) for this loan paid?: By mortgage lender/broker",
  "x48d" = "How were the total closing costs (loan costs and other costs) for this loan paid?: By seller/builder",
  "x48x" = "How were the total closing costs (loan costs and other costs) for this loan paid?: Other (specify)",
  "x48z" = "How were the total closing costs (loan costs and other costs) for this loan paid?: Loan had no closing costs (Waves 1...",
  "x49" = "Were the loan costs you paid similar to what you had expected to pay based on the Loan Estimates or Closing Disclosur...",
  "x5001" = "After closing on this mortgage, how much cash reserves in checking, savings, and other similar assets did you have re...",
  "x50a" = "Did you seek input about your closing documents from any of the following people?: Mortgage lender/broker",
  "x50b" = "Did you seek input about your closing documents from any of the following people?: Settlement/closing agent",
  "x50c" = "Did you seek input about your closing documents from any of the following people?: Real estate agent",
  "x50d" = "Did you seek input about your closing documents from any of the following people?: Personal attorney",
  "x50e" = "Did you seek input about your closing documents from any of the following people?: Title insurance agent",
  "x50f" = "Did you seek input about your closing documents from any of the following people?: Trusted friend or relative who is ...",
  "x50g" = "Did you seek input about your closing documents from any of the following people?: Housing counselor",
  "x51a" = "At any time after you made your final loan application did any of the following change?: Monthly payment (Waves 11-42)",
  "x51b" = "At any time after you made your final loan application did any of the following change?: Interest rate (Waves 11-42)",
  "x51c" = "At any time after you made your final loan application did any of the following change?: Other fees (Waves 11-42)",
  "x51d" = "At any time after you made your final loan application did any of the following change?: Amount of money needed to cl...",
  "x53a" = "Did you face any of the following at your loan closing?: Loan documents not ready at closing (Waves 19-42)",
  "x53a_1" = "What unpleasant surprises did you face at your loan closing?: Loan documents not ready (Waves 11-18)",
  "x53b" = "Did you face any of the following at your loan closing?: Closing did not occur as originally scheduled (Waves 19-42)",
  "x53b_1" = "What unpleasant surprises did you face at your loan closing?: Closing did not occur as originally scheduled (Waves 11...",
  "x53c" = "Did you face any of the following at your loan closing?: Three day rule required re-disclosure (Waves 19-42)",
  "x53c_1" = "What unpleasant surprises did you face at your loan closing?: Three day rule required re-disclosure (Waves 11-18)",
  "x53d" = "Did you face any of the following at your loan closing?: Mortgage terms different at closing than expected, e.g. inte...",
  "x53d1_1" = "What unpleasant surprises did you face?: Different loan terms (Waves 1-10)",
  "x53d2_1" = "What unpleasant surprises did you face?: Higher monthly payment (Waves 1-10)",
  "x53d3_1" = "What unpleasant surprises did you face?: Higher interest rate (Waves 1-10)",
  "x53d_1" = "What unpleasant surprises did you face at your loan closing?: Mortgage terms different at closing e.g. interest rate,...",
  "x53e" = "Did you face any of the following at your loan closing?: More cash needed at closing than expected, e.g. escrow, unex...",
  "x53e1_1" = "What unpleasant surprises did you face?: Unexpected fees (Waves 1-10)",
  "x53e2_1" = "What unpleasant surprises did you face?: Higher amount of money needed at closing (Waves 1-10)",
  "x53e_1" = "What unpleasant surprises did you face at your loan closing?: More cash needed at closing e.g. escrow, unexpected fee...",
  "x53f" = "Did you face any of the following at your loan closing?: Asked to sign blank documents at closing (Waves 19-42)",
  "x53f_1" = "What unpleasant surprises did you face at your loan closing?: Asked to sign blank documents (Waves 1-18)",
  "x53g" = "Did you face any of the following at your loan closing?: Felt rushed at closing or not given time to read documents (...",
  "x53g_1" = "What unpleasant surprises did you face at your loan closing?: Felt rushed at closing or not given time to read docume...",
  "x53h" = "Did you face any of the following at your loan closing?: Asked to sign pre-dated or post-dated documents at closing (...",
  "x53i" = "Did you face any of the following at your loan closing?: Less cash needed at closing than expected (Waves 19-42)",
  "x54" = "At the same time you took out this mortgage, did you also take out another loan on the property you financed with thi...",
  "x56a" = "How well could you explain to someone the...: Process of taking out a mortgage",
  "x56b" = "How well could you explain to someone the...: Difference between a fixed- and an adjustable-rate mortgage",
  "x56c" = "How well could you explain to someone the...: Difference between a prime and subprime loan",
  "x56d" = "How well could you explain to someone the...: Difference between a mortgage\'s interest rate and its APR",
  "x56e" = "How well could you explain to someone the...: Amortization of a loan",
  "x56f" = "How well could you explain to someone the...: Consequences of not making required mortgage payments",
  "x56g" = "How well could you explain to someone the...: Difference between lender\'s and owner\'s title insurance (Waves 7-42)",
  "x56h" = "How well could you explain to someone the...: Relationship between discount points and interest rate (Waves 11-42)",
  "x56i" = "How well could you explain to someone the...: Reason payments into an escrow account can change (Waves 11-42)",
  "x59" = "Which one of the following best describes how you acquired this property?",
  "x60" = "Which one of the following best describes this property?",
  "x61" = "Does this mortgage cover more than one unit? (Waves 7-42)",
  "x63" = "Do you rent out all or any portion of this property?",
  "x65" = "Besides you, the mortgage co-signers, and renters, does anyone else help pay the expenses for this property? (Waves 7...",
  "x66" = "Which one of the following best describes how you use this property?",
  "x6701" = "Which one of the following best describes your willingness or ability to move from your primary residence? (Waves 31-42)",
  "x68a" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Number ...",
  "x68b" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Number ...",
  "x68c" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Number ...",
  "x68d" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Number ...",
  "x68e" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: House p...",
  "x68f" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Overall...",
  "x68g" = "In the last couple years, how have the following changed in the neighborhood where this property is located?: Number ...",
  "x69" = "What do you think will happen to the prices of homes in this neighborhood over the next couple of years?",
  "x70" = "In the next couple of years, how do you expect the overall desirability of living in this neighborhood to change?",
  "x71a" = "How likely is it that in the next couple of years you will...: Sell this property",
  "x71b" = "How likely is it that in the next couple of years you will...: Move but keep this property",
  "x71c" = "How likely is it that in the next couple of years you will...: Refinance the mortgage on this property",
  "x71d" = "How likely is it that in the next couple of years you will...: Pay off this mortgage and own the property mortgage-free",
  "x72" = "What is your current marital status?",
  "x73" = "Do you have a partner who shares the decision-making and responsibilities of running your household but is not your l...",
  "x74r" = "Age at last birthday: Respondent",
  "x75r" = "Sex: Respondent",
  "x76r" = "Highest level of education achieved: Respondent",
  "x76s" = "Highest level of education achieved: Spouse/Partner",
  "x77r" = "Hispanic or Latino: Respondent",
  "x78r" = "Race: Respondent",
  "x79ra" = "Current work status 1: Respondent (work status selected by respondent involving the most employment)",
  "x79rb" = "Current work status 2: Respondent (if a second work status was selected)",
  "x79sa" = "Current work status 1: Spouse/Partner (work status selected by spouse/partner involving the most employment)",
  "x79sb" = "Current work status 2: Spouse/Partner (if a second work status was selected)",
  "x80r" = "Ever served on active duty in the U.S. Armed Forces, Reserves or National Guard?: Respondent (Waves 15-42)",
  "x80r_1" = "Ever served on active duty in the U.S. Armed Forces: (Active duty includes serving in the U.S. Armed Forces as well a...",
  "x80s" = "Ever served on active duty in the U.S. Armed Forces, Reserves or National Guard?: Spouse/Partner (Waves 15-42)",
  "x80s_1" = "Ever served on active duty in the U.S. Armed Forces: (Active duty includes serving in the U.S. Armed Forces as well a...",
  "x81a" = "Besides you (and your spouse/partner) who else lives in your household?: Children/grandchildren under age 18 (Waves 7...",
  "x81b" = "Besides you (and your spouse/partner) who else lives in your household?: Children/grandchildren age 18-22 (Waves 7-42)",
  "x81c" = "Besides you (and your spouse/partner) who else lives in your household?: Children/grandchildren age 23 or older (Wave...",
  "x81d" = "Besides you (and your spouse/partner) who else lives in your household?: Parents of you or your spouse or partner (Wa...",
  "x81e" = "Besides you (and your spouse/partner) who else lives in your household?: Other relatives like siblings or cousins (Wa...",
  "x81f" = "Besides you (and your spouse/partner) who else lives in your household?: Non-relative (Waves 7-42)",
  "x81z" = "Besides you (and your spouse/partner) who else lives in your household?: No one else (Waves 7-42)",
  "x82" = "Do you speak a language other than English at home? (Waves 13-42)",
  "x8201" = "Was it important to get your mortgage documents in this language? (Waves 25-42)",
  "x8202" = "Did you get mortgage documents in this language? (Waves 25-42)",
  "x83" = "Approximately how much is your total annual household income from all sources (wages, salaries, tips, interest, child...",
  "x84" = "How does this total annual household income compare to what it is in a \'normal\' year?",
  "x85a" = "Does your total annual household income include any of the following sources?: Wages or salary",
  "x85b" = "Does your total annual household income include any of the following sources?: Business or self-employment",
  "x85c" = "Does your total annual household income include any of the following sources?: Interest or dividends",
  "x85d" = "Does your total annual household income include any of the following sources?: Alimony or child support",
  "x85e" = "Does your total annual household income include any of the following sources?: Social Security, pension or other reti...",
  "x86a" = "Does anyone in your household have any of the following?: 401(k), 403(b), IRA, or pension plan",
  "x86b" = "Does anyone in your household have any of the following?: Stocks, bonds, or mutual funds (not in retirement accounts ...",
  "x86c" = "Does anyone in your household have any of the following?: Certificates of deposit",
  "x86d" = "Does anyone in your household have any of the following?: Investment real estate",
  "x87" = "Which one of the following statements best describes the amount of financial risk you are willing to take when you sa...",
  "x88a" = "Do you agree or disagree with the following statements?: Owning a home is a good financial investment",
  "x88b" = "Do you agree or disagree with the following statements?: Most mortgage lenders generally treat borrowers well",
  "x88c" = "Do you agree or disagree with the following statements?: Most mortgage lenders would offer me roughly the same rates ...",
  "x88d" = "Do you agree or disagree with the following statements?: Late payments will lower my credit rating",
  "x88e" = "Do you agree or disagree with the following statements?: Lenders shouldn\'t care about any late payments, only whethe...",
  "x88f" = "Do you agree or disagree with the following statements?: It is okay to default or stop making mortgage payments if it...",
  "x88g" = "Do you agree or disagree with the following statements?: I would consider counseling or taking a course about managin...",
  "x89a" = "In the last couple of years, have any of the following happened to you?: Separated, divorced, or partner left",
  "x89b" = "In the last couple of years, have any of the following happened to you?: Married, remarried or new partner",
  "x89c" = "In the last couple of years, have any of the following happened to you?: Death of a household member",
  "x89d" = "In the last couple of years, have any of the following happened to you?: Addition to your household (not spouse/partner)",
  "x89e" = "In the last couple of years, have any of the following happened to you?: Person leaving your household (not spouse/pa...",
  "x89f" = "In the last couple of years, have any of the following happened to you?: Disability or serious illness of household m...",
  "x89g" = "In the last couple of years, have any of the following happened to you?: Disaster affecting a property you own",
  "x89h" = "In the last couple of years, have any of the following happened to you?: Disaster affecting your (or your spouse/part...",
  "x89i" = "In the last couple of years, have any of the following happened to you?: Moved within the area (less than 50 miles)",
  "x89j" = "In the last couple of years, have any of the following happened to you?: Moved to a new area (50 miles or more)",
  "x90a" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Layoff, unemploymen...",
  "x90b" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Retirement (Waves 4...",
  "x90c" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Promotion",
  "x90d" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Starting a new job",
  "x90e" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Starting a second job",
  "x90f" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: Business failure",
  "x90g" = "In the last couple of years, have any of the following happened to you (or your spouse/partner)?: A personal financia...",
  "x91a" = "In the last couple of years, how have the following changed for you (and your spouse/partner)?: Household income",
  "x91b" = "In the last couple of years, how have the following changed for you (and your spouse/partner)?: Housing expenses",
  "x91c" = "In the last couple of years, how have the following changed for you (and your spouse/partner)?: Non-housing expenses",
  "x92a" = "In the next couple of years, how do you expect the following to change for you (and your spouse/partner)?: Household ...",
  "x92b" = "In the next couple of years, how do you expect the following to change for you (and your spouse/partner)?: Housing ex...",
  "x92c" = "In the next couple of years, how do you expect the following to change for you (and your spouse/partner)?: Non-housin...",
  "x93a" = "How likely is it that in the next couple of years you (or your spouse/partner) will face...: Retirement",
  "x93b" = "How likely is it that in the next couple of years you (or your spouse/partner) will face...: Difficulties making your...",
  "x93c" = "How likely is it that in the next couple of years you (or your spouse/partner) will face...: A layoff, unemployment, ...",
  "x93d" = "How likely is it that in the next couple of years you (or your spouse/partner) will face...: Some other personal fina...",
  "x94a" = "If your household faced an unexpected personal financial crisis in the next couple of years, how likely is it you cou...",
  "x94b" = "If your household faced an unexpected personal financial crisis in the next couple of years, how likely is it you cou...",
  "x94c" = "If your household faced an unexpected personal financial crisis in the next couple of years, how likely is it you cou...",
  "x94d" = "If your household faced an unexpected personal financial crisis in the next couple of years, how likely is it you cou...",
  "z35" = "Z35: What percent of the purchase price was the down payment to buy this property (including money from a prior home ...",
  "z38" = "Z38: Approximately how much was owed, in total, on the old mortgage(s) and loan(s) you refinanced? (Indicator)",
  "z41" = "Z41: When you took out this most recent mortgage or refinance, what was the dollar amount you borrowed? (Indicator)",
  "z42" = "Z42: What is the monthly payment, including the amount paid to escrow for taxes and insurance? (Indicator)",
  "z43" = "Z43: What is the interest rate on this mortgage? (Indicator)",
  "z47" = "Z47: The \'Closing Disclosure\' statement you received at closing shows the loan closing costs and other closing cost...",
  "z55" = "Z55: What was the amount of this loan? (Indicator)",
  "z57" = "Z57: When did you first become the owner of this property? (Indicator)",
  "z58" = "Z58: What was the purchase price of this property, or if you built it, the construction and land cost? (Indicator)",
  "z62" = "Z62: About how much do you think this property is worth in terms of what you could sell it for now? (Indicator)",
  "z64" = "Z64: How much rent do you receive annually? (Indicator)",
  "z67" = "Z67: If primary residence, when did you move into this property? (Indicator)"
)

# Helper: return label with raw-code fallback (visually flagged)


get_variable_label <- function(var_code) {
  label <- variable_labels[[var_code]]
  if (is.null(label)) return(var_code)   # fallback: raw code (should not happen with full SAS labels)
  label
}

# ============================================================
# SIGNIFICANCE HELPERS
# ============================================================
test_significance <- function(data, var, group_var, weight_var = "analysis_weight") {
  test_data <- data %>% filter(!is.na(get(var)), !is.na(get(group_var)))
  if (nrow(test_data) < 10) return(list(p_value = NA, significant = FALSE))
  groups <- unique(test_data[[group_var]])
  if (length(groups) != 2) return(list(p_value = NA, significant = FALSE))
  var_binary <- paste0(var, "_binary")
  group1_data <- test_data %>% filter(get(group_var) == groups[1])
  group2_data <- test_data %>% filter(get(group_var) == groups[2])
  g1_pos <- sum(group1_data$analysis_weight * (group1_data[[var_binary]] == "Positive (Very/Somewhat)"), na.rm = TRUE)
  g1_neg <- sum(group1_data$analysis_weight * (group1_data[[var_binary]] == "Negative (Not at all)"), na.rm = TRUE)
  g2_pos <- sum(group2_data$analysis_weight * (group2_data[[var_binary]] == "Positive (Very/Somewhat)"), na.rm = TRUE)
  g2_neg <- sum(group2_data$analysis_weight * (group2_data[[var_binary]] == "Negative (Not at all)"), na.rm = TRUE)
  cont_table <- matrix(c(round(g1_pos), round(g1_neg), round(g2_pos), round(g2_neg)), nrow = 2, byrow = TRUE)
  tryCatch({
    res <- chisq.test(cont_table, correct = FALSE)
    list(p_value = res$p.value, significant = res$p.value < 0.05)
  }, error = function(e) list(p_value = NA, significant = FALSE))
}

sig_label <- function(p) {
  if (is.na(p)) return("")
  if (p < 0.001) return("***")
  if (p < 0.01)  return("**")
  if (p < 0.05)  return("*")
  return("")
}

# ============================================================
# DATA PREPROCESSING
# ============================================================
cat("Loading NSMO data...\n")
data <- readRDS("nsmo.rds")

# ── Format-aware binary coding lookup (from nsmo_v60_labels.sas) ────────────
# Maps each survey variable to its SAS format code so we can apply the
# correct positive/negative coding per scale type.
# Format-aware positive/negative coding lookup
# Built from nsmo_v60_labels.sas format assignments
nsmo_var_format <- c(
  "x05a" = "PVERYFM",
  "x05b" = "PVERYFM",
  "x05c" = "PVERYFM",
  "x05d" = "PVERYFM",
  "x05e" = "PVERYFM",
  "x05f" = "PVERYFM",
  "x05g" = "PVERYFM",
  "x06" = "PVERYFM",
  "x07" = "PIDEAFM",
  "x08a" = "PLOTFM",
  "x08b" = "PLOTFM",
  "x08c" = "PLOTFM",
  "x08d" = "PLOTFM",
  "x08e" = "PLOTFM",
  "x08f" = "PLOTFM",
  "x08g" = "PLOTFM",
  "x08h" = "PLOTFM",
  "x08i" = "PLOTFM",
  "x09" = "PPICKFM",
  "x10" = "PAPPFM",
  "x11" = "PLENDFM",
  "x12" = "PLENDFM",
  "x13a" = "PYNFM",
  "x13b" = "PYNFM",
  "x13c" = "PYNFM",
  "x13d" = "PYNFM",
  "x14a" = "PIMPFM",
  "x14a_1" = "PVERYFM",
  "x14b" = "PIMPFM",
  "x14b_1" = "PVERYFM",
  "x14c" = "PIMPFM",
  "x14c_1" = "PVERYFM",
  "x14d" = "PIMPFM",
  "x14d_1" = "PVERYFM",
  "x14e" = "PIMPFM",
  "x14f" = "PIMPFM",
  "x14f_1" = "PVERYFM",
  "x14g" = "PIMPFM",
  "x14g_1" = "PVERYFM",
  "x14h" = "PIMPFM",
  "x14h_1" = "PVERYFM",
  "x14i" = "PIMPFM",
  "x14i_1" = "PVERYFM",
  "x14j" = "PIMPFM",
  "x14k" = "PIMPFM",
  "x15" = "PCONFM",
  "x16" = "PVERYFM",
  "x1601" = "PINTERACT",
  "x17a" = "PIMPFM",
  "x17a_1" = "PVERYFM",
  "x17b" = "PIMPFM",
  "x17b_1" = "PVERYFM",
  "x17c" = "PIMPFM",
  "x17c_1" = "PVERYFM",
  "x17d" = "PIMPFM",
  "x17d_1" = "PVERYFM",
  "x17e" = "PIMPFM",
  "x17e_1" = "PVERYFM",
  "x17f" = "PIMPFM",
  "x17f_1" = "PVERYFM",
  "x17g" = "PIMPFM",
  "x17g_1" = "PVERYFM",
  "x17h" = "PIMPFM",
  "x17h_1" = "PVERYFM",
  "x18" = "PYNFM",
  "x19" = "PYNFM",
  "x20a" = "PYNFM",
  "x20b" = "PYNFM",
  "x20c" = "PYNFM",
  "x20d" = "PYNFM",
  "x20e" = "PYNFM",
  "x20f" = "PYNFM",
  "x20g" = "PYNFM",
  "x20h" = "PYNFM",
  "x20i" = "PYNFM",
  "x20j" = "PYNFM",
  "x21a" = "PYNFM",
  "x21b" = "PYNFM",
  "x21c" = "PYNFM",
  "x22a" = "PYNFM",
  "x22b" = "PYNFM",
  "x22c" = "PYNFM",
  "x23a" = "PYNFM",
  "x23b" = "PYNFM",
  "x23c" = "PYNFM",
  "x23d" = "PYNFM",
  "x23e" = "PYNFM",
  "x23f" = "PYNFM",
  "x23g" = "PYNFM",
  "x23h" = "PYNFM",
  "x23i" = "PYNFM",
  "x23j" = "PYNFM",
  "x24a" = "PYNFM",
  "x24b" = "PYNFM",
  "x24c" = "PYNFM",
  "x24z" = "PYNFM",
  "x25" = "PYNFM",
  "x25_1" = "PYNFM",
  "x26" = "PTIFM",
  "x27a" = "PVERYFM",
  "x27b" = "PVERYFM",
  "x27c" = "PVERYFM",
  "x28a" = "PVERYFM",
  "x28b" = "PVERYFM",
  "x28c" = "PVERYFM",
  "x28d" = "PVERYFM",
  "x28e" = "PVERYFM",
  "x28f" = "PVERYFM",
  "x28g" = "PVERYFM",
  "x28h" = "PVERYFM",
  "x29" = "PYNFM",
  "x30a" = "PYNFM",
  "x30b" = "PYNFM",
  "x30c" = "PYNFM",
  "x30d" = "PYNFM",
  "x30e" = "PYNFM",
  "x31" = "PCOUNFM",
  "x32" = "PVERYFM",
  "x33" = "PPURPFM",
  "x34a" = "PTIMEFM",
  "x34b" = "PTIMEFM",
  "x34c" = "PTIMEFM",
  "x34d" = "PTIMEFM",
  "x34e" = "PTIMEFM",
  "x36a" = "PUSEDFM",
  "x36b" = "PUSEDFM",
  "x36c" = "PUSEDFM",
  "x36d" = "PUSEDFM",
  "x36e" = "PUSEDFM",
  "x36f" = "PUSEDFM",
  "x37a" = "PIMPFM",
  "x37a_1" = "PVERYFM",
  "x37b" = "PIMPFM",
  "x37b_1" = "PVERYFM",
  "x37c" = "PIMPFM",
  "x37c_1" = "PVERYFM",
  "x37d" = "PIMPFM",
  "x37d_1" = "PVERYFM",
  "x37e" = "PIMPFM",
  "x37e_1" = "PVERYFM",
  "x37f" = "PIMPFM",
  "x37f_1" = "PVERYFM",
  "x37g" = "PIMPFM",
  "x40a" = "PYNFM",
  "x40b" = "PYNFM",
  "x40c" = "PYNFM",
  "x40d" = "PYNFM",
  "x40e" = "PYNFM",
  "x40f" = "PYNFM",
  "x40g" = "PYNFM",
  "x40h" = "PYNFM",
  "x40x" = "PYNFM",
  "x40z" = "PYNFM",
  "x44" = "PYNFM",
  "x45" = "PINTFM",
  "x46a" = "PYNFM",
  "x46b" = "PYNFM",
  "x46c" = "PYNFM",
  "x46d" = "PYNFM",
  "x46e" = "PYNFM",
  "x46f" = "PYNFM",
  "x48a" = "PYNFM",
  "x48b" = "PYNFM",
  "x48c" = "PYNFM",
  "x48d" = "PYNFM",
  "x48x" = "PYNFM",
  "x48z" = "PYNFM",
  "x49" = "PYNFM",
  "x5001" = "PRESERVE",
  "x50a" = "PYNFM",
  "x50b" = "PYNFM",
  "x50c" = "PYNFM",
  "x50d" = "PYNFM",
  "x50e" = "PYNFM",
  "x50f" = "PYNFM",
  "x50g" = "PYNFM",
  "x51a" = "PSAMEFM",
  "x51b" = "PSAMEFM",
  "x51c" = "PSAMEFM",
  "x51d" = "PSAMEFM",
  "x53a" = "PYNFM",
  "x53a_1" = "PYNFM",
  "x53b" = "PYNFM",
  "x53b_1" = "PYNFM",
  "x53c" = "PYNFM",
  "x53c_1" = "PYNFM",
  "x53d" = "PYNFM",
  "x53d1_1" = "PYNFM",
  "x53d2_1" = "PYNFM",
  "x53d3_1" = "PYNFM",
  "x53d_1" = "PYNFM",
  "x53e" = "PYNFM",
  "x53e1_1" = "PYNFM",
  "x53e2_1" = "PYNFM",
  "x53e_1" = "PYNFM",
  "x53f" = "PYNFM",
  "x53f_1" = "PYNFM",
  "x53g" = "PYNFM",
  "x53g_1" = "PYNFM",
  "x53h" = "PYNFM",
  "x53i" = "PYNFM",
  "x54" = "PYNFM",
  "x56a" = "PVERYFM",
  "x56b" = "PVERYFM",
  "x56c" = "PVERYFM",
  "x56d" = "PVERYFM",
  "x56e" = "PVERYFM",
  "x56f" = "PVERYFM",
  "x56g" = "PVERYFM",
  "x56h" = "PVERYFM",
  "x56i" = "PVERYFM",
  "x59" = "PACQFM",
  "x60" = "PPROPFM",
  "x61" = "PYNFM",
  "x63" = "PYNFM",
  "x65" = "PYNFM",
  "x66" = "POCCFM",
  "x6701" = "PWILLING",
  "x68a" = "PCHANGEFM",
  "x68b" = "PCHANGEFM",
  "x68c" = "PCHANGEFM",
  "x68d" = "PCHANGEFM",
  "x68e" = "PCHANGEFM",
  "x68f" = "PCHANGEFM",
  "x68g" = "PCHANGEFM",
  "x69" = "PPRICEFM",
  "x70" = "PDESIREFM",
  "x71a" = "PVERYFM",
  "x71b" = "PVERYFM",
  "x71c" = "PVERYFM",
  "x71d" = "PVERYFM",
  "x72" = "PMARRYFM",
  "x73" = "PYNFM",
  "x74r" = "PAGEFM",
  "x75r" = "PSEXFM",
  "x76r" = "PEDUCFM",
  "x76s" = "PEDUCFM",
  "x77r" = "PYNFM",
  "x78r" = "PRACEFM",
  "x79ra" = "PEMPLOYFM",
  "x79rb" = "PEMPLOYFM",
  "x79sa" = "PEMPLOYFM",
  "x79sb" = "PEMPLOYFM",
  "x80r" = "PVETFM",
  "x80r_1" = "PVETXFM",
  "x80s" = "PVETFM",
  "x80s_1" = "PVETXFM",
  "x81a" = "PYNFM",
  "x81b" = "PYNFM",
  "x81c" = "PYNFM",
  "x81d" = "PYNFM",
  "x81e" = "PYNFM",
  "x81f" = "PYNFM",
  "x81z" = "PYNFM",
  "x82" = "PYNFM",
  "x8201" = "PYNFM",
  "x8202" = "PYNFM",
  "x83" = "PINCFM",
  "x84" = "PNORMFM",
  "x85a" = "PYNFM",
  "x85b" = "PYNFM",
  "x85c" = "PYNFM",
  "x85d" = "PYNFM",
  "x85e" = "PYNFM",
  "x86a" = "PYNFM",
  "x86b" = "PYNFM",
  "x86c" = "PYNFM",
  "x86d" = "PYNFM",
  "x87" = "PRISKFM",
  "x88a" = "PAGREEFM",
  "x88b" = "PAGREEFM",
  "x88c" = "PAGREEFM",
  "x88d" = "PAGREEFM",
  "x88e" = "PAGREEFM",
  "x88f" = "PAGREEFM",
  "x88g" = "PAGREEFM",
  "x89a" = "PYNFM",
  "x89b" = "PYNFM",
  "x89c" = "PYNFM",
  "x89d" = "PYNFM",
  "x89e" = "PYNFM",
  "x89f" = "PYNFM",
  "x89g" = "PYNFM",
  "x89h" = "PYNFM",
  "x89i" = "PYNFM",
  "x89j" = "PYNFM",
  "x90a" = "PYNFM",
  "x90b" = "PYNFM",
  "x90c" = "PYNFM",
  "x90d" = "PYNFM",
  "x90e" = "PYNFM",
  "x90f" = "PYNFM",
  "x90g" = "PYNFM",
  "x91a" = "PCHANGEFM",
  "x91b" = "PCHANGEFM",
  "x91c" = "PCHANGEFM",
  "x92a" = "PCHANGEFM",
  "x92b" = "PCHANGEFM",
  "x92c" = "PCHANGEFM",
  "x93a" = "PVERYFM",
  "x93b" = "PVERYFM",
  "x93c" = "PVERYFM",
  "x93d" = "PVERYFM",
  "x94a" = "PVERYFM",
  "x94b" = "PVERYFM",
  "x94c" = "PVERYFM",
  "x94d" = "PVERYFM"
)

# For each format, define which raw values = Positive and which = Negative.
# All other values (including -2=N/A, -3=wave N/A) become NA.
nsmo_format_coding <- list(
  # 1=Very/Satisfied/Likely/Open/Helpful, 2=Somewhat, 3=Not at all
  PVERYFM   = list(pos = c(1, 2), neg = c(3)),
  # 1=A Lot, 2=A Little, 3=Not At All
  PLOTFM    = list(pos = c(1, 2), neg = c(3)),
  # 1=Yes, 2=No  (most binary survey items)
  PYNFM     = list(pos = c(1),    neg = c(2)),
  # 1=Important, 2=Not important
  PIMPFM    = list(pos = c(1),    neg = c(2)),
  # 1=Agree, 2=Disagree
  PAGREEFM  = list(pos = c(1),    neg = c(2)),
  # 1=Used, 2=Not Used
  PUSEDFM   = list(pos = c(1),    neg = c(2)),
  # 1=Before Offer, 2=After Offer, 3=Did not do → did it (before or after) = positive
  PTIMEFM   = list(pos = c(1, 2), neg = c(3)),
  # 1=Sig Increase, 2=Little/No Change, 3=Sig Decrease → stable/up = positive
  PCHANGEFM = list(pos = c(1, 2), neg = c(3)),
  # x51: 1=Higher (bad), 2=Same, 3=Lower → same or lower cost = positive
  PSAMEFM   = list(pos = c(2, 3), neg = c(1))
)

preprocess_data <- function(df) {
  # Detect survey response variables: x-prefix, numeric, ≤10 distinct
  # valid values (1-10). Negative codes like -2, -3 are N/A markers and
  # are intentionally excluded from the uniqueness/range check.
  response_vars <- names(df)[grepl("^x[0-9]", names(df)) &
    sapply(df, function(x) {
      vals <- na.omit(x)
      pos_vals <- vals[vals > 0]   # ignore -2, -3 not-applicable codes
      is.numeric(x) &&
        length(pos_vals) > 0 &&
        length(unique(pos_vals)) <= 10 &&
        all(pos_vals %in% 1:10)
    })]

  # Apply format-aware binary coding to each response variable
  df_processed <- df
  for (v in response_vars) {
    fmt    <- nsmo_var_format[v]
    coding <- if (!is.na(fmt) && !is.null(nsmo_format_coding[[fmt]])) {
      nsmo_format_coding[[fmt]]
    } else {
      list(pos = c(1, 2), neg = c(3))   # safe default: Very/Somewhat = positive
    }
    raw <- df_processed[[v]]
    df_processed[[paste0(v, "_binary")]] <- case_when(
      raw %in% coding$pos ~ "Positive (Very/Somewhat)",
      raw %in% coding$neg ~ "Negative (Not at all)",
      TRUE                ~ NA_character_
    )
  }

  df_processed <- df_processed %>%
    mutate(
      Age           = coalesce(age_o1, age_o2),
      # Age_Category: prefer survey self-report (x74r); fall back to numeric Age from Experian
      Age_num       = coalesce(age_o1, age_o2),
      Age_Category  = case_when(
        x74r == 1 ~ "18-24", x74r == 2 ~ "25-34", x74r == 3 ~ "35-44",
        x74r == 4 ~ "45-54", x74r == 5 ~ "55-64", x74r == 6 ~ "65-74",
        x74r == 7 ~ "75+",
        !is.na(Age_num) & Age_num >= 18 & Age_num < 25 ~ "18-24",
        !is.na(Age_num) & Age_num >= 25 & Age_num < 35 ~ "25-34",
        !is.na(Age_num) & Age_num >= 35 & Age_num < 45 ~ "35-44",
        !is.na(Age_num) & Age_num >= 45 & Age_num < 55 ~ "45-54",
        !is.na(Age_num) & Age_num >= 55 & Age_num < 65 ~ "55-64",
        !is.na(Age_num) & Age_num >= 65 & Age_num < 75 ~ "65-74",
        !is.na(Age_num) & Age_num >= 75                ~ "75+",
        TRUE ~ "Unknown"),
      Sex       = coalesce(sex_o1, sex_o2),
      Sex_Label = case_when(
        Sex == 1 | x75r == 1 ~ "Male",
        Sex == 2 | x75r == 2 ~ "Female",
        TRUE ~ "Unknown"),
      Education_Max   = pmax(x76r, x76s, na.rm = TRUE),
      Education_Label = case_when(
        Education_Max == 1 ~ "Some High School",
        Education_Max == 2 ~ "High School Graduate",
        Education_Max == 3 ~ "Tech School",
        Education_Max == 4 ~ "Some College",
        Education_Max == 5 ~ "College Graduate",
        Education_Max == 6 ~ "Post-Graduate",
        TRUE ~ "Unknown"),
      Hispanic = case_when(x77r == 1 ~ "Yes", x77r == 2 ~ "No", TRUE ~ "Unknown"),
      Race = case_when(
        x78r == 1 ~ "White", x78r == 2 ~ "Black",
        x78r == 3 ~ "Asian", x78r == 4 ~ "Other", TRUE ~ "Unknown"),
      Work_Status = case_when(
        x79ra %in% c(1,2) | (!is.na(x79rb) & is.na(x79ra) & x79rb %in% c(1,2)) ~ "Self-Employed",
        x79ra %in% c(3,4) | (!is.na(x79rb) & is.na(x79ra) & x79rb %in% c(3,4)) ~ "Employed",
        x79ra == 5        | (!is.na(x79rb) & is.na(x79ra) & x79rb == 5)         ~ "Retired",
        x79ra == 6        | (!is.na(x79rb) & is.na(x79ra) & x79rb == 6)         ~ "Unemployed",
        x79ra == 7        | (!is.na(x79rb) & is.na(x79ra) & x79rb == 7)         ~ "Not Working",
        TRUE ~ "Unknown"),
      Veteran = case_when(x80r %in% c(3,4) ~ "Yes", !is.na(x80r) ~ "No", TRUE ~ "Unknown")
    )

  df_processed <- df_processed %>%
    mutate(
      First_Mortgage       = coalesce(first_mort_r, first_mort_s),
      First_Mortgage_Label = case_when(
        First_Mortgage == 1 ~ "First Mortgage",
        First_Mortgage == 2 ~ "Not First",
        TRUE ~ "Unknown"),
      Score_Origin = coalesce(score_orig_r, score_orig_s),
      FICO         = Score_Origin,
      FICO_category = case_when(
        Score_Origin >= 800 ~ "Exceptional (800+)",
        Score_Origin >= 740 ~ "Very Good (740-799)",
        Score_Origin >= 670 ~ "Good (670-739)",
        Score_Origin >= 580 ~ "Fair (580-669)",
        Score_Origin <  580 ~ "Poor (<580)",
        TRUE ~ "Unknown"),
      Amount_Borrowed  = z41,
      Monthly_Payment  = z42,
      # z43 is an indicator code, NOT a decimal rate — compute true rate from PMMS + spread
      Interest_Rate    = ifelse(!is.na(pmms) & !is.na(rate_spread), pmms + rate_spread, NA_real_),
      Amount_Category  = case_when(
        loan_amount_cat %in% 1:8 ~ "Under $400K",
        loan_amount_cat == 9     ~ "Over $400K",
        TRUE ~ "Unknown"),
      Term_Label = case_when(
        term == 30      ~ "30 Years",
        !is.na(term)    ~ "Other",
        TRUE ~ "Unknown"),
      LTV_Category = case_when(
        ltv <= 80 ~ "≤80%", ltv <= 90 ~ "80-90%",
        ltv <= 95 ~ "90-95%", ltv > 95 ~ ">95%", TRUE ~ "Unknown"),
      CLTV_Category = case_when(
        cltv <= 80 ~ "≤80%", cltv <= 90 ~ "80-90%",
        cltv <= 95 ~ "90-95%", cltv > 95 ~ ">95%", TRUE ~ "Unknown"),
      DTI_Category = case_when(
        dti <= 36 ~ "≤36%", dti <= 43 ~ "36-43%",
        dti <= 50 ~ "43-50%", dti > 50 ~ ">50%", TRUE ~ "Unknown"),
      Loan_Type = case_when(
        loan_type == 1            ~ "Conventional",
        loan_type %in% c(2,3,4)  ~ "FHA/VA/FSA",
        TRUE ~ "Unknown"),
      GSE_Label = case_when(
        gse %in% c(1,2,3) ~ "GSE", !is.na(gse) ~ "Other", TRUE ~ "Unknown"),
      Metro = case_when(
        metro_lmi %in% c(1,2) ~ "MSA", !is.na(metro_lmi) ~ "Non-MSA", TRUE ~ "Unknown"),
      Jumbo_Label = case_when(
        jumbo == 1 ~ "Jumbo", jumbo == 2 ~ "Non-Jumbo", TRUE ~ "Unknown"),
      Cashout_Label = case_when(
        cashout == 1 ~ "Refinance", cashout == 2 ~ "Purchase", TRUE ~ "Unknown"),
      Rate_Spread_Pct = rate_spread,
      PMMS_Pct        = pmms
    )

  forb_cols <- names(df_processed)[grepl("^forb", names(df_processed), ignore.case = TRUE)]
  if (length(forb_cols) > 0) {
    df_processed <- df_processed %>%
      rowwise() %>%
      mutate(Forbearance = ifelse(any(c_across(all_of(forb_cols)) == 1, na.rm = TRUE), "Yes", "No")) %>%
      ungroup()
  } else {
    df_processed$Forbearance <- "No"
  }

  perf_cols <- names(df_processed)[grepl("^perf_status", names(df_processed), ignore.case = TRUE)]
  if (length(perf_cols) > 0) {
    df_processed <- df_processed %>%
      rowwise() %>%
      mutate(
        Last_Perf_Status = {
          pv <- c_across(all_of(perf_cols)); pv <- pv[!is.na(pv)]
          if (length(pv) > 0) pv[length(pv)] else NA_real_
        },
        Performance = case_when(
          Last_Perf_Status == 2              ~ "60 Days Delinquent",
          Last_Perf_Status == 6              ~ "180+ Days Delinquent",
          Last_Perf_Status %in% c(7,8,9)    ~ "Foreclosure/Bankruptcy",
          !is.na(Last_Perf_Status)           ~ "Current/Other",
          TRUE ~ "Unknown")
      ) %>% ungroup()
  } else {
    df_processed$Performance <- "Unknown"
  }

  score_r_cols <- names(df_processed)[grepl("^score_[0-9]{4}_r$", names(df_processed), ignore.case = TRUE)]
  score_s_cols <- names(df_processed)[grepl("^score_[0-9]{4}_s$", names(df_processed), ignore.case = TRUE)]
  if (length(score_r_cols) > 0 || length(score_s_cols) > 0) {
    df_processed <- df_processed %>%
      rowwise() %>%
      mutate(Score_Last = {
        sr <- if (length(score_r_cols) > 0) c_across(all_of(score_r_cols)) else numeric(0)
        sr <- sr[!is.na(sr)]
        ss <- if (length(score_s_cols) > 0) c_across(all_of(score_s_cols)) else numeric(0)
        ss <- ss[!is.na(ss)]
        if (length(sr) > 0) sr[length(sr)]
        else if (length(ss) > 0) ss[length(ss)]
        else NA_real_
      }) %>% ungroup()
  } else {
    df_processed$Score_Last <- NA_real_
  }

  if ("open_year" %in% names(df) && "open_month" %in% names(df)) {
    df_processed <- df_processed %>%
      mutate(
        loan_date   = as.Date(paste(open_year, open_month, "01", sep = "-")),
        COVID_period = case_when(
          loan_date < as.Date("2020-03-01")  ~ "Pre-COVID (Before Mar 2020)",
          loan_date < as.Date("2021-07-01")  ~ "COVID (Mar 2020 - Jun 2021)",
          TRUE                               ~ "Post-COVID (Jul 2021+)")
      )
  } else {
    df_processed$COVID_period <- "Period Not Available"
  }

  if ("cu" %in% names(df)) {
    df_processed <- df_processed %>%
      mutate(Institution_Type = ifelse(cu == 1, "Credit Union", "Non-Credit Union"))
  } else {
    df_processed$Institution_Type <- "Type Not Available"
  }

  list(data = df_processed, response_vars = response_vars)
}

processed     <- preprocess_data(data)
df            <- processed$data
response_vars <- processed$response_vars

# ── Curated short display labels for response variable dropdown ──────────────
# Used by response_choices (description picker). Max ~55 chars each.
response_short_labels <- list(
  "x05a" = "Familiarity: Mortgage interest rates",
  "x05b" = "Familiarity: Types of mortgages available",
  "x05c" = "Familiarity: The mortgage process",
  "x05d" = "Familiarity: Down payment requirements",
  "x05e" = "Familiarity: Income needed to qualify",
  "x05f" = "Familiarity: Your credit history/score",
  "x05g" = "Familiarity: Money needed at closing",
  "x06" = "Concern about qualifying for a mortgage",
  "x07" = "How firm an idea you had about the mortgage",
  "x08a" = "Info source: Your mortgage lender/broker",
  "x08b" = "Info source: Other mortgage lenders/brokers",
  "x08c" = "Info source: Real estate agents or builders",
  "x08d" = "Info source: Material in the mail",
  "x08e" = "Info source: Mortgage websites",
  "x08f" = "Info source: Newspaper / TV / Radio",
  "x08g" = "Info source: Friends, relatives, co-workers",
  "x08h" = "Info source: Bankers, CUs, financial planners",
  "x08i" = "Info source: Housing counselors",
  "x09" = "Shopping: Loan type first vs lender first",
  "x10" = "Shopping: How mortgage was applied for",
  "x11" = "Shopping: # of lenders seriously considered",
  "x12" = "Shopping: # of lenders actually applied to",
  "x13a" = "Multi-lender: Searching for better loan terms",
  "x13b" = "Multi-lender: Concern over qualifying",
  "x13c" = "Multi-lender: Info from Loan Estimate",
  "x13d" = "Multi-lender: Turned down on earlier application",
  "x14a" = "Lender choice: Established banking relationship",
  "x14a_1" = "Lender choice: Established banking relationship (early)",
  "x14b" = "Lender choice: Local office or branch nearby",
  "x14b_1" = "Lender choice: Local office or branch (early)",
  "x14c" = "Lender choice: Used previously for a mortgage",
  "x14c_1" = "Lender choice: Used previously (early)",
  "x14d" = "Lender choice: Is a personal friend or relative",
  "x14d_1" = "Lender choice: Personal friend or relative (early)",
  "x14e" = "Lender choice: Paperless online process",
  "x14f" = "Lender choice: Friend/relative recommendation",
  "x14f_1" = "Lender choice: Friend/relative rec. (early)",
  "x14g" = "Lender choice: Real estate agent recommendation",
  "x14g_1" = "Lender choice: Agent recommendation (early)",
  "x14h" = "Lender choice: Reputation of lender",
  "x14h_1" = "Lender choice: Reputation of lender (early)",
  "x14i" = "Lender choice: Speaks my primary language",
  "x14i_1" = "Lender choice: Speaks my language (early)",
  "x14j" = "Lender choice: Documents in my language",
  "x14k" = "Lender choice: Disability accommodations",
  "x15" = "Who initiated first contact with lender",
  "x16" = "Openness to lender suggestions",
  "x1601" = "Primary interaction method with lender",
  "x17a" = "Mortgage factor: Lower interest rate",
  "x17a_1" = "Mortgage factor: Low interest rate (early)",
  "x17b" = "Mortgage factor: Lower APR",
  "x17b_1" = "Mortgage factor: Low APR (early)",
  "x17c" = "Mortgage factor: Lower closing fees",
  "x17c_1" = "Mortgage factor: Low closing fees (early)",
  "x17d" = "Mortgage factor: Lower down payment",
  "x17d_1" = "Mortgage factor: Low down payment (early)",
  "x17e" = "Mortgage factor: Lower monthly payment",
  "x17e_1" = "Mortgage factor: Low monthly payment (early)",
  "x17f" = "Mortgage factor: Fixed rate for life of loan",
  "x17f_1" = "Mortgage factor: Fixed rate (early)",
  "x17g" = "Mortgage factor: 30-year term",
  "x17g_1" = "Mortgage factor: Term < 30 years (early)",
  "x17h" = "Mortgage factor: No mortgage insurance",
  "x17h_1" = "Mortgage factor: No mortgage insurance (early)",
  "x18" = "Received Home Loan Toolkit booklet",
  "x19" = "Toolkit booklet led to additional questions",
  "x20a" = "Process: Had to add another co-signer",
  "x20b" = "Process: Resolved credit report errors",
  "x20c" = "Process: Answered follow-up income/asset requests",
  "x20d" = "Process: Had more than one appraisal",
  "x20e" = "Process: Redid paperwork due to delays",
  "x20f" = "Process: Delayed or postponed closing",
  "x20g" = "Process: Loan Estimate was revised",
  "x20h" = "Process: Checked other sources to confirm terms",
  "x20i" = "Process: Got docs in non-English language",
  "x20j" = "Process: Lender translated to primary language",
  "x21a" = "Loan Estimate: Had easy-to-understand info",
  "x21b" = "Loan Estimate: Contained valuable information",
  "x21c" = "Loan Estimate: Caused you to take an action",
  "x22a" = "Loan Estimate led to: Asking lender questions",
  "x22b" = "Loan Estimate led to: Seeking loan/closing change",
  "x22c" = "Loan Estimate led to: Applying to different lender",
  "x23a" = "Informed about: Fixed-rate mortgage",
  "x23b" = "Informed about: Adjustable-rate mortgage",
  "x23c" = "Informed about: Term < 30 years",
  "x23d" = "Informed about: Higher rate / lower closing costs",
  "x23e" = "Informed about: Lower rate / discount points",
  "x23f" = "Informed about: Interest-only payments",
  "x23g" = "Informed about: Escrow account",
  "x23h" = "Informed about: Prepayment penalty",
  "x23i" = "Informed about: Reduced documentation / easy approval",
  "x23j" = "Informed about: FHA / VA / USDA loan",
  "x24a" = "Closing agent: Recommended by lender/agent",
  "x24b" = "Closing agent: Used previously",
  "x24c" = "Closing agent: Found by shopping around",
  "x24z" = "Closing agent: Did not use one",
  "x25" = "Have title insurance",
  "x25_1" = "Lender required title insurance",
  "x26" = "How title insurance provider was chosen",
  "x27a" = "Best deal: Terms fit your needs",
  "x27b" = "Best deal: Lowest rate you could qualify for",
  "x27c" = "Best deal: Lowest closing costs",
  "x28a" = "Satisfaction: Mortgage lender/broker",
  "x28b" = "Satisfaction: Application process",
  "x28c" = "Satisfaction: Documentation process",
  "x28d" = "Satisfaction: Loan closing process",
  "x28e" = "Satisfaction: Mortgage disclosure documents",
  "x28f" = "Satisfaction: Timeliness of disclosures",
  "x28g" = "Satisfaction: Settlement agent",
  "x28h" = "Satisfaction: Property appraisal",
  "x29" = "Took home-buying course or counseling",
  "x30a" = "Counseling format: In person, one-on-one",
  "x30b" = "Counseling format: In person, group",
  "x30c" = "Counseling format: Over the phone",
  "x30d" = "Counseling format: Online",
  "x30e" = "Counseling: Was required",
  "x31" = "Hours of home-buying counseling",
  "x32" = "How helpful was home-buying counseling",
  "x33" = "Primary reason for this mortgage",
  "x34a" = "Pre-offer: Contacted lender to explore options",
  "x34b" = "Pre-offer: Got pre-approval/pre-qualification",
  "x34c" = "Pre-offer: Decided on loan type",
  "x34d" = "Pre-offer: Decided on which lender to use",
  "x34e" = "Pre-offer: Submitted official loan application",
  "x36a" = "Funds source: Sale of another property",
  "x36b" = "Funds source: Savings / retirement / inheritance",
  "x36c" = "Funds source: Nonprofit or gov assistance",
  "x36d" = "Funds source: Second lien / HELOC",
  "x36e" = "Funds source: Gift or loan from family/friend",
  "x36f" = "Funds source: Seller contribution",
  "x37a" = "Refi reason: Switch to fixed-rate loan",
  "x37a_1" = "Refi reason: Switch to fixed rate (early)",
  "x37b" = "Refi reason: Get lower interest rate",
  "x37b_1" = "Refi reason: Lower interest rate (early)",
  "x37c" = "Refi reason: Get lower monthly payment",
  "x37c_1" = "Refi reason: Lower monthly payment (early)",
  "x37d" = "Refi reason: Consolidate / pay down debt",
  "x37d_1" = "Refi reason: Consolidate debt (early)",
  "x37e" = "Refi reason: Repay loan more quickly",
  "x37e_1" = "Refi reason: Repay more quickly (early)",
  "x37f" = "Refi reason: Take out cash",
  "x37f_1" = "Refi reason: Take out cash (early)",
  "x37g" = "Refi reason: Remove private mortgage insurance",
  "x40a" = "Cash-out used for: College expenses",
  "x40b" = "Cash-out used for: Auto or major purchase",
  "x40c" = "Cash-out used for: Buy out co-signer/co-owner",
  "x40d" = "Cash-out used for: Pay off other debts",
  "x40e" = "Cash-out used for: Home repairs / construction",
  "x40f" = "Cash-out used for: Savings",
  "x40g" = "Cash-out used for: Closing costs of new mortgage",
  "x40h" = "Cash-out used for: Business or investment",
  "x40x" = "Cash-out used for: Other",
  "x40z" = "Did not receive cash from refinancing",
  "x44" = "Mortgage has: Adjustable rate",
  "x45" = "How interest rate decision was made",
  "x46a" = "Mortgage has: Prepayment penalty",
  "x46b" = "Mortgage has: Escrow for taxes/insurance",
  "x46c" = "Mortgage has: Balloon payment",
  "x46d" = "Mortgage has: Interest-only payments",
  "x46e" = "Mortgage has: Private mortgage insurance",
  "x46f" = "Mortgage has: Lender-required flood insurance",
  "x48a" = "Closing costs paid: By check/wire transfer",
  "x48b" = "Closing costs paid: Added to loan amount",
  "x48c" = "Closing costs paid: By lender credit",
  "x48d" = "Closing costs paid: By seller/builder",
  "x48x" = "Closing costs paid: Other arrangement",
  "x48z" = "Closing costs: Loan had no closing costs",
  "x49" = "Closing costs similar to what was expected",
  "x5001" = "Cash reserves remaining after closing",
  "x50a" = "Closing docs reviewed with: Mortgage lender",
  "x50b" = "Closing docs reviewed with: Settlement agent",
  "x50c" = "Closing docs reviewed with: Real estate agent",
  "x50d" = "Closing docs reviewed with: Personal attorney",
  "x50e" = "Closing docs reviewed with: Title agent",
  "x50f" = "Closing docs reviewed with: Friend/relative",
  "x50g" = "Closing docs reviewed with: Housing counselor",
  "x51a" = "Post-application change: Monthly payment",
  "x51b" = "Post-application change: Interest rate",
  "x51c" = "Post-application change: Other fees",
  "x51d" = "Post-application change: Cash needed to close",
  "x53a" = "Closing issue: Loan documents not ready",
  "x53a_1" = "Closing surprise: Loan docs not ready (early)",
  "x53b" = "Closing issue: Closing not as scheduled",
  "x53b_1" = "Closing surprise: Not as scheduled (early)",
  "x53c" = "Closing issue: Three-day rule re-disclosure",
  "x53c_1" = "Closing surprise: Three-day re-disclosure (early)",
  "x53d" = "Closing issue: Mortgage terms different than expected",
  "x53d1_1" = "Closing surprise: Different loan terms",
  "x53d2_1" = "Closing surprise: Higher monthly payment",
  "x53d3_1" = "Closing surprise: Higher interest rate",
  "x53d_1" = "Closing surprise: Different terms (early)",
  "x53e" = "Closing issue: More cash needed than expected",
  "x53e1_1" = "Closing surprise: Unexpected fees",
  "x53e2_1" = "Closing surprise: More cash needed",
  "x53e_1" = "Closing surprise: More cash needed (early)",
  "x53f" = "Closing issue: Asked to sign blank documents",
  "x53f_1" = "Closing surprise: Sign blank docs (early)",
  "x53g" = "Closing issue: Felt rushed at closing",
  "x53g_1" = "Closing surprise: Felt rushed (early)",
  "x53h" = "Closing issue: Asked to sign pre/post-dated docs",
  "x53i" = "Closing issue: Less cash needed than expected",
  "x54" = "Took out a second loan at same time",
  "x56a" = "Literacy: Explain taking out a mortgage",
  "x56b" = "Literacy: Fixed vs adjustable-rate mortgage",
  "x56c" = "Literacy: Prime vs subprime loan",
  "x56d" = "Literacy: Interest rate vs APR",
  "x56e" = "Literacy: Loan amortization",
  "x56f" = "Literacy: Consequences of missed payments",
  "x56g" = "Literacy: Lenders vs owners title insurance",
  "x56h" = "Literacy: Discount points vs interest rate",
  "x56i" = "Literacy: Why escrow payments change",
  "x59" = "How property was acquired",
  "x60" = "Property type",
  "x61" = "Mortgage covers more than one unit",
  "x63" = "Rents out all or part of property",
  "x65" = "Someone else helps pay property expenses",
  "x66" = "How property is used",
  "x6701" = "Willingness or ability to move",
  "x68a" = "Neighborhood change: Homes for sale",
  "x68b" = "Neighborhood change: Vacant homes",
  "x68c" = "Neighborhood change: Homes for rent",
  "x68d" = "Neighborhood change: Foreclosures/short sales",
  "x68e" = "Neighborhood change: House prices",
  "x68f" = "Neighborhood change: Overall desirability",
  "x68g" = "Neighborhood change: Homes hit by disasters",
  "x69" = "Expected change in home prices nearby",
  "x70" = "Expected change in neighborhood desirability",
  "x71a" = "Likelihood of selling property",
  "x71b" = "Likelihood of moving (keeping property)",
  "x71c" = "Likelihood of refinancing",
  "x71d" = "Likelihood of paying off mortgage early",
  "x72" = "Current marital status",
  "x73" = "Has a non-married decision-making partner",
  "x74r" = "Age: Respondent",
  "x75r" = "Sex: Respondent",
  "x76r" = "Education level: Respondent",
  "x76s" = "Education level: Spouse/Partner",
  "x77r" = "Hispanic or Latino: Respondent",
  "x78r" = "Race: Respondent",
  "x79ra" = "Work status (primary): Respondent",
  "x79rb" = "Work status (secondary): Respondent",
  "x79sa" = "Work status (primary): Spouse/Partner",
  "x79sb" = "Work status (secondary): Spouse/Partner",
  "x80r" = "Military service: Respondent",
  "x80r_1" = "Military service: Respondent (early)",
  "x80s" = "Military service: Spouse/Partner",
  "x80s_1" = "Military service: Spouse/Partner (early)",
  "x81a" = "Household: Children/grandchildren under 18",
  "x81b" = "Household: Children/grandchildren 18-22",
  "x81c" = "Household: Children/grandchildren 23+",
  "x81d" = "Household: Parents or in-laws",
  "x81e" = "Household: Other relatives",
  "x81f" = "Household: Non-relative",
  "x81z" = "Household: No one else",
  "x82" = "Speaks non-English language at home",
  "x8201" = "Important to get mortgage docs in home language",
  "x8202" = "Received mortgage docs in home language",
  "x83" = "Total annual household income",
  "x84" = "Income vs normal year",
  "x85a" = "Income includes: Wages or salary",
  "x85b" = "Income includes: Business/self-employment",
  "x85c" = "Income includes: Interest or dividends",
  "x85d" = "Income includes: Alimony or child support",
  "x85e" = "Income includes: Social Security / pension",
  "x86a" = "Assets: 401k / IRA / pension plan",
  "x86b" = "Assets: Stocks, bonds, mutual funds",
  "x86c" = "Assets: Certificates of deposit",
  "x86d" = "Assets: Investment real estate",
  "x87" = "Financial risk tolerance",
  "x88a" = "Attitude: Owning a home is a good investment",
  "x88b" = "Attitude: Lenders generally treat borrowers well",
  "x88c" = "Attitude: Lenders offer similar rates to all",
  "x88d" = "Attitude: Late payments lower credit rating",
  "x88e" = "Attitude: Lenders shouldnt care about late payments",
  "x88f" = "Attitude: OK to default if in borrowers interest",
  "x88g" = "Attitude: Would consider financial counseling",
  "x89a" = "Life event: Separated or divorced",
  "x89b" = "Life event: Married or new partner",
  "x89c" = "Life event: Death of household member",
  "x89d" = "Life event: New household addition",
  "x89e" = "Life event: Person left household",
  "x89f" = "Life event: Disability or serious illness",
  "x89g" = "Life event: Disaster affecting property",
  "x89h" = "Life event: Disaster affecting work",
  "x89i" = "Life event: Moved (< 50 miles)",
  "x89j" = "Life event: Moved to new area (50+ miles)",
  "x90a" = "Work event: Layoff or reduced hours",
  "x90b" = "Work event: Retirement",
  "x90c" = "Work event: Promotion",
  "x90d" = "Work event: Starting a new job",
  "x90e" = "Work event: Starting a second job",
  "x90f" = "Work event: Business failure",
  "x90g" = "Work event: Personal financial crisis",
  "x91a" = "Recent change: Household income",
  "x91b" = "Recent change: Housing expenses",
  "x91c" = "Recent change: Non-housing expenses",
  "x92a" = "Expected change: Household income",
  "x92b" = "Expected change: Housing expenses",
  "x92c" = "Expected change: Non-housing expenses",
  "x93a" = "Upcoming risk: Retirement",
  "x93b" = "Upcoming risk: Mortgage payment difficulties",
  "x93c" = "Upcoming risk: Layoff or reduced hours",
  "x93d" = "Upcoming risk: Other financial crisis",
  "x94a" = "Crisis resilience: Cover bills 3 months",
  "x94b" = "Crisis resilience: Get help from family/friends",
  "x94c" = "Crisis resilience: Borrow from bank/CU",
  "x94d" = "Crisis resilience: Significantly increase income"
)

# ── Dropdown 1: Variable CODE picker — shows raw code (e.g. "X05A") ──────────
response_choices_code <- setNames(response_vars, toupper(response_vars))

# ── Dropdown 2: Description picker — shows concise label only (no code prefix)
# Falls back to the full SAS label sub-part if not in curated list.
response_choices <- setNames(response_vars,
  sapply(response_vars, function(v) {
    # Try curated short label first
    short <- response_short_labels[[v]]
    if (!is.null(short)) return(short)
    # Fallback: extract sub-question from full SAS label
    lbl <- get_variable_label(v)
    if (grepl(": ", lbl, fixed = TRUE)) {
      parts <- strsplit(lbl, ": ", fixed = TRUE)[[1]]
      lbl   <- trimws(paste(parts[-1], collapse = ": "))
    }
    lbl <- gsub("\\s*\\(Waves[^)]+\\)\\s*$", "", lbl)
    lbl <- trimws(lbl)
    if (nchar(lbl) > 55) paste0(substr(lbl, 1, 52), "...") else lbl
  }))

available_years <- sort(unique(df$open_year[!is.na(df$open_year)]))

fico_order <- c("Poor (<580)", "Fair (580-669)", "Good (670-739)",
                "Very Good (740-799)", "Exceptional (800+)")
period_order <- c("Pre-COVID (Before Mar 2020)", "COVID (Mar 2020 - Jun 2021)", "Post-COVID (Jul 2021+)")

# Legacy aliases kept for backward compat
colors_cu       <- v2_colors$cu
colors_noncu    <- v2_colors$noncu
colors_positive <- v2_colors$positive
colors_negative <- v2_colors$negative

# ============================================================
# SHARED PLOTLY THEME HELPER
# ============================================================
v2_plotly_layout <- function(p, title = NULL, xlab = NULL, ylab = NULL,
                              legend_bottom = TRUE, margin = list(t = 50, b = 60, l = 60, r = 30)) {
  p <- p %>% layout(
    font        = list(family = "Inter, Segoe UI, sans-serif", color = v2_colors$text_primary),
    paper_bgcolor = "rgba(0,0,0,0)",
    plot_bgcolor  = "rgba(0,0,0,0)",
    margin        = margin,
    xaxis = list(showgrid = FALSE, zeroline = FALSE, title = xlab,
                 tickfont = list(size = 11)),
    yaxis = list(showgrid = TRUE, gridcolor = "#E2E8F0", zeroline = FALSE, title = ylab,
                 tickfont = list(size = 11))
  )
  if (!is.null(title)) {
    p <- p %>% layout(title = list(text = title, font = list(size = 14, color = v2_colors$text_primary)))
  }
  if (legend_bottom) {
    p <- p %>% layout(legend = list(orientation = "h", x = 0.3, y = -0.25,
                                    font = list(size = 11)))
  }
  p
}

cat("✅ V2 global.R loaded.\n")
cat(sprintf("   Observations : %s\n", format(nrow(df), big.mark = ",")))
cat(sprintf("   Response vars: %d\n", length(response_vars)))
cat(sprintf("   Years        : %d – %d\n", min(available_years, na.rm = TRUE), max(available_years, na.rm = TRUE)))
